// <auto-generated />
namespace Retailer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class item_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(item_change));
        
        string IMigrationMetadata.Id
        {
            get { return "202009041811380_item_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
