// <auto-generated />
namespace Retailer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class wishlist_change_userId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wishlist_change_userId));
        
        string IMigrationMetadata.Id
        {
            get { return "202009011548097_wishlist_change_userId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
