// <auto-generated />
namespace Retailer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Profile_foreignkey_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Profile_foreignkey_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202009030344221_Profile_foreignkey_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
